on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install -e .[dev]  # pytest, pytest-cov
          pip install coveralls

      - name: Run tests with coverage
        run: pytest --cov=blayers --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github